version: "2.1"
services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
      - /home/pi/Programs/Dashy/conf.yml:/app/public/conf.yml
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
      - UID=1001
      - GID=100
    restart: unless-stopped